
export type CompanyStage =
  | "Pre-Seed"
  | "Seed"
  | "Series A"
  | "Series B"
  | "Series C"
  | "Series D"
  | "Venture";

export type CompanySector =
  | "AI & Machine Learning"
  | "AI"
  | "Web3/Crypto"
  | "Blockchain"
  | "Developer Tools"
  | "Enterprise Software"
  | "E-commerce"
  | "E-Commerce"
  | "FinTech"
  | "Fintech"
  | "HealthTech"
  | "EdTech"
  | "PropTech"
  | "Clean Energy"
  | "Climate Tech"
  | "Marketing Technology"
  | "Business and Productivity Software"
  | "Procurement Tech"
  | "Marketplace"
  | "Logistics"
  | "SaaS"
  | "Automotive"
  | "Energy"
  | "Construction Technology"
  | "Home Services"
  | "Communication Software"
  | "Industrial Technology"
  | "Medical Technology"
  | "HR Tech"
  | "Sales Tech"
  | "Event Technology"
  | "Legal Tech"
  | "Media and Information Services"
  | "Advertising Technology"
  | "Travel Technology"
  | "Data Infrastructure"
  | "Recreation Tech"
  | "InsurTech"
  | "FoodTech"
  | "AgTech"
  | "Market Intelligence"
  | "Manufacturing"
  | "Customer Experience Technology"
  | "Recruitment Technology"
  | "Retail Technology"
  | "Professional Training and Coaching"
  | "Government Technology"
  | "Sustainability Technology"
  | "Childcare Services"
  | "Business Intelligence"
  | "Entertainment Software"
  | "Customer Support Technology"
  | "Mobility"
  | "Nonprofit Tech";

export type CompanyLocation =
  | "Abu Dhabi"
  | "Amsterdam"
  | "Arlington"
  | "Atlanta"
  | "Austin"
  | "Bend"
  | "Berlin"
  | "Berwyn"
  | "Boston"
  | "Brooklyn"
  | "Brookline"
  | "Campbell"
  | "Canton"
  | "Charlotte"
  | "Chicago"
  | "Columbus"
  | "Denver"
  | "Des Moines"
  | "Detroit"
  | "Distributed"
  | "Dublin"
  | "Fort Collins"
  | "Foster City"
  | "George Town"
  | "Greenwood Village"
  | "Holmdel"
  | "Irvine"
  | "Jersey City"
  | "Kansas City"
  | "Karlsruhe"
  | "Lehi"
  | "Lewes"
  | "London"
  | "Los Altos"
  | "Los Angeles"
  | "Medellín"
  | "Menlo Park"
  | "Miami"
  | "Middletown"
  | "Munich"
  | "Newton"
  | "New York"
  | "North Miami Beach"
  | "Oakland"
  | "Omaha"
  | "Or Yehuda"
  | "Palo Alto"
  | "Paris"
  | "Phoenix"
  | "Portland"
  | "Raleigh"
  | "Redmond"
  | "Redwood City"
  | "Salt Lake City"
  | "San Francisco"
  | "San Jose"
  | "San Mateo"
  | "San Rafael"
  | "Santa Ana"
  | "Santa Cruz"
  | "São Paulo"
  | "Seattle"
  | "Silver Spring"
  | "Singapore"
  | "Stamford"
  | "Stockholm"
  | "Sunnyvale"
  | "Sydney"
  | "Tel Aviv"
  | "Tokyo"
  | "Toronto"
  | "Vancouver"
  | "Washington"
  | "West Hollywood"
  | "West Palm Beach"
  | "Woodstock"
  | "Youngstown";

export type OfficePreference =
  | "Remote"
  | "Hybrid"
  | "In-Office";

export type TrackingPreferences = {
  stages: CompanyStage[];
  sectors: CompanySector[];
  locations: CompanyLocation[];
  office_preferences: OfficePreference[];
};

export const COMPANY_STAGES: CompanyStage[] = [
  "Pre-Seed",
  "Seed",
  "Series A",
  "Series B",
  "Series C",
  "Series D",
  "Venture"
];

export const OFFICE_PREFERENCES: OfficePreference[] = [
  "Remote",
  "Hybrid",
  "In-Office"
];
