// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://boibtyufrcuruntqgeoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvaWJ0eXVmcmN1cnVudHFnZW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1NzcwMjgsImV4cCI6MjA1NTE1MzAyOH0.tZxmRCr9S6T45tPlaGkEX4k5WxFNI1XFWqB7Qv8cj1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);